#!/usr/bin/env php
<?php

// Comment out the following lines when you put the application in production
defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'dev');

require __DIR__ . '/vendor/autoload.php';
require __DIR__ . '/vendor/yiisoft/yii2/Yii.php';

$config = require __DIR__ . '/config/console.php';

$application = new \Dacheng\Yii2\Swoole\Console\CoroutineApplication($config);
$exitCode = $application->run();
exit($exitCode);
